import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});
import "./globals.css";

//Componnets
import Header from "@/components/ui/Header";
import PageTransitionLayout from "./PageTransitionLayout";
import StairTransition from "./StairTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} antialiased`}>
        <Header />
        <PageTransitionLayout>{children}</PageTransitionLayout>
        <StairTransition />
      </body>
    </html>
  );
}
